# opcode (https://github.com/DannyBen/opcode)

## Script Generation

generate: bashly generate --upgrade "$@"
#? Generate the script

watch: bashly generate --watch
#? Watch source files and regenerate the script


## Testing and Linting

check:
  op generate
  op shellcheck
  op shfmt
  op test
  op spell
  green "ALL CHECKS PASS"
#? Generate and run all checks

test: shellkin "$@"
#? Run Shellkin feature tests

shellcheck: shellcheck pm setup uninstall && green "PASS shellcheck"
#? Run ShellCheck

shfmt: shfmt -ci -i 2 -d pm setup uninstall && green "PASS shfmt"
#? Run shfmt

spell: typos && green "PASS typos"
#? Run spell check
