#!/usr/bin/env bash
# This script was generated by bashly 1.4.0 (https://bashly.dev)
# Modifying it manually is not recommended

if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
  printf "bash version 4.2 or higher is required\n" >&2
  exit 1
fi

version_command() {
  echo "$version"
}

pm_usage() {
  printf "pm - A friendly interface for pacman\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm COMMAND\n"
  printf "  pm [COMMAND] --help | -h\n"
  printf "  pm --version | -v\n"
  echo

  printf "%s\n" "$(bold "Package Management Commands:")"
  printf "  %s   Update package databases and upgrade the system\n" "$(green "update")     "
  printf "  %s   Install packages\n" "$(green "install")    "
  printf "  %s   Remove packages and their unneeded dependencies\n" "$(green "remove")     "
  printf "  %s   Update the Arch Linux keyring\n" "$(green "update-keys")"
  echo
  printf "%s\n" "$(bold "Package Query Commands:")"
  printf "  %s   List package names\n" "$(green "list")       "
  printf "  %s   Show package information\n" "$(green "info")       "
  printf "  %s   Search packages\n" "$(green "search")     "
  printf "  %s   Find packages that provide a command\n" "$(green "provides")   "
  printf "  %s   Browse packages interactively\n" "$(green "browse")     "
  printf "  %s   Show which installed package owns a file\n" "$(green "origin")     "
  echo
  printf "%s\n" "$(bold "Internal Commands:")"
  printf "  %s   Generate bash completions.\n" "$(green "completions")"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo
    printf "  %s\n" "$(green "--version, -v")"
    printf "    Show version number\n"
    echo

  fi
}

pm_update_usage() {
  printf "pm update - Update package databases and upgrade the system\n\n"
  printf "Alias: u\n"
  echo

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm update\n"
  printf "  pm update --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

  fi
}

pm_install_usage() {
  printf "pm install - Install packages\n\n"
  printf "Alias: add\n"
  echo

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm install PACKAGE...\n"
  printf "  pm install --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

    printf "%s\n" "$(bold "Arguments:")"

    printf "  %s\n" "$(green "PACKAGE...")"
    printf "    Package name\n"
    echo

    printf "%s\n" "$(bold "Examples:")"
    printf "  pm install git\n"
    printf "  pm install git fzf\n"
    echo

  fi
}

pm_remove_usage() {
  printf "pm remove - Remove packages and their unneeded dependencies\n\n"
  printf "Alias: rm\n"
  echo

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm remove PACKAGE...\n"
  printf "  pm remove --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

    printf "%s\n" "$(bold "Arguments:")"

    printf "  %s\n" "$(green "PACKAGE...")"
    printf "    Package name\n"
    echo

    printf "%s\n" "$(bold "Examples:")"
    printf "  pm remove git\n"
    echo

  fi
}

pm_update_keys_usage() {
  printf "pm update-keys - Update the Arch Linux keyring\n\n"
  printf "Alias: keys\n"
  echo

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm update-keys\n"
  printf "  pm update-keys --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

  fi
}

pm_list_usage() {
  printf "pm list - List package names\n\n"
  printf "Alias: ls\n"
  echo

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm list [OPTIONS]\n"
  printf "  pm list --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--available, -a")"
    printf "    List available repository packages instead of installed packages\n"
    echo

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

  fi
}

pm_info_usage() {
  printf "pm info - Show package information\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm info PACKAGE... [OPTIONS]\n"
  printf "  pm info --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--available, -a")"
    printf "    Query available repository packages instead of installed packages\n"
    echo

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

    printf "%s\n" "$(bold "Arguments:")"

    printf "  %s\n" "$(green "PACKAGE...")"
    printf "    Package name\n"
    echo

    printf "%s\n" "$(bold "Examples:")"
    printf "  pm info git\n"
    printf "  pm info git --available\n"
    echo

  fi
}

pm_search_usage() {
  printf "pm search - Search packages\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm search QUERY... [OPTIONS]\n"
  printf "  pm search --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--available, -a")"
    printf "    Search available repository packages instead of installed packages\n"
    echo

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

    printf "%s\n" "$(bold "Arguments:")"

    printf "  %s\n" "$(green "QUERY...")"
    printf "    Search expression\n"
    echo

    printf "%s\n" "$(bold "Examples:")"
    printf "  pm search terminal emulator\n"
    printf "  pm search terminal emulator --available\n"
    echo

  fi
}

pm_provides_usage() {
  printf "pm provides - Find packages that provide a command\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm provides COMMAND\n"
  printf "  pm provides --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

    printf "%s\n" "$(bold "Arguments:")"

    printf "  %s\n" "$(green "COMMAND")"
    printf "    Command name\n"
    echo

    printf "%s\n" "$(bold "Examples:")"
    printf "  pm provides convert\n"
    echo

  fi
}

pm_browse_usage() {
  printf "pm browse - Browse packages interactively\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm browse [OPTIONS]\n"
  printf "  pm browse --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--available, -a")"
    printf "    Browse available repository packages instead of installed packages\n"
    echo

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

  fi
}

pm_origin_usage() {
  printf "pm origin - Show which installed package owns a file\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm origin PATH...\n"
  printf "  pm origin --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

    printf "%s\n" "$(bold "Arguments:")"

    printf "  %s\n" "$(green "PATH...")"
    printf "    File path\n"
    echo

    printf "%s\n" "$(bold "Examples:")"
    printf "  pm origin /usr/bin/git\n"
    echo

  fi
}

pm_completions_usage() {
  printf "pm completions - Generate bash completions.\n\n"

  printf "%s\n" "$(bold "Usage:")"
  printf "  pm completions\n"
  printf "  pm completions --help | -h\n"
  echo

  if [[ -n "$long_usage" ]]; then

    printf "%s\n" "$(bold "Options:")"

    printf "  %s\n" "$(green "--help, -h")"
    printf "    Show this help\n"
    echo

  fi
}

normalize_input() {
  local arg passthru flags
  passthru=false

  while [[ $# -gt 0 ]]; do
    arg="$1"
    if [[ $passthru == true ]]; then
      input+=("$arg")
    elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
      input+=("${BASH_REMATCH[1]}")
      input+=("${BASH_REMATCH[2]}")
    elif [[ $arg =~ ^-([a-zA-Z0-9][a-zA-Z0-9]+)$ ]]; then
      flags="${BASH_REMATCH[1]}"
      for ((i = 0; i < ${#flags}; i++)); do
        input+=("-${flags:i:1}")
      done
    elif [[ "$arg" == "--" ]]; then
      passthru=true
      input+=("$arg")
    else
      input+=("$arg")
    fi

    shift
  done
}

enable_auto_colors() {
  if [[ -z ${NO_COLOR+x} && ! -t 1 ]]; then
    NO_COLOR=1
  fi
}

print_in_color() {
  local color="$1"
  shift
  if [[ "${NO_COLOR:-}" == "" ]]; then
    printf "$color%b\e[0m\n" "$*"
  else
    printf "%b\n" "$*"
  fi
}

red() { print_in_color "\e[31m" "$*"; }
green() { print_in_color "\e[32m" "$*"; }
yellow() { print_in_color "\e[33m" "$*"; }
blue() { print_in_color "\e[34m" "$*"; }
magenta() { print_in_color "\e[35m" "$*"; }
cyan() { print_in_color "\e[36m" "$*"; }
black() { print_in_color "\e[30m" "$*"; }
white() { print_in_color "\e[37m" "$*"; }

bold() { print_in_color "\e[1m" "$*"; }
underlined() { print_in_color "\e[4m" "$*"; }
bold_underlined() { print_in_color "\e[1;4m" "$*"; }

red_bold() { print_in_color "\e[1;31m" "$*"; }
green_bold() { print_in_color "\e[1;32m" "$*"; }
yellow_bold() { print_in_color "\e[1;33m" "$*"; }
blue_bold() { print_in_color "\e[1;34m" "$*"; }
magenta_bold() { print_in_color "\e[1;35m" "$*"; }
cyan_bold() { print_in_color "\e[1;36m" "$*"; }
black_bold() { print_in_color "\e[1;30m" "$*"; }
white_bold() { print_in_color "\e[1;37m" "$*"; }

red_underlined() { print_in_color "\e[4;31m" "$*"; }
green_underlined() { print_in_color "\e[4;32m" "$*"; }
yellow_underlined() { print_in_color "\e[4;33m" "$*"; }
blue_underlined() { print_in_color "\e[4;34m" "$*"; }
magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
black_underlined() { print_in_color "\e[4;30m" "$*"; }
white_underlined() { print_in_color "\e[4;37m" "$*"; }

send_completions() {
  echo $'# pm completion                                            -*- shell-script -*-'
  echo $''
  echo $'# This bash completions script was generated by'
  echo $'# completely (https://github.com/bashly-framework/completely)'
  echo $'# Modifying it manually is not recommended'
  echo $''
  echo $'_pm_completions_node_flag_state() {'
  echo $'  case "$1:$2" in'
  echo $'    0:--help|0:-h) return 0 ;;'
  echo $'    0:--version|0:-v) return 0 ;;'
  echo $'    1:--help|1:-h) return 0 ;;'
  echo $'    2:--help|2:-h) return 0 ;;'
  echo $'    3:--help|3:-h) return 0 ;;'
  echo $'    4:--help|4:-h) return 0 ;;'
  echo $'    5:--help|5:-h) return 0 ;;'
  echo $'    5:--available|5:-a) return 0 ;;'
  echo $'    6:--help|6:-h) return 0 ;;'
  echo $'    6:--available|6:-a) return 0 ;;'
  echo $'    7:--help|7:-h) return 0 ;;'
  echo $'    7:--available|7:-a) return 0 ;;'
  echo $'    8:--help|8:-h) return 0 ;;'
  echo $'    9:--help|9:-h) return 0 ;;'
  echo $'    9:--available|9:-a) return 0 ;;'
  echo $'    10:--help|10:-h) return 0 ;;'
  echo $'    11:--help|11:-h) return 0 ;;'
  echo $'  esac'
  echo $''
  echo $'  return 1'
  echo $'}'
  echo $''
  echo $'_pm_completions_option_seen() {'
  echo $'  local completed_option option_name'
  echo $'  for completed_option in "${completed_options[@]}"; do'
  echo $'    for option_name in "$@"; do'
  echo $'      [[ "$completed_option" == "$option_name" ]] && return 0'
  echo $'    done'
  echo $'  done'
  echo $''
  echo $'  return 1'
  echo $'}'
  echo $''
  echo $'_pm_completions_resolve_node() {'
  echo $'  node_id=0'
  echo $'  node_word_count=0'
  echo $'  positional_index=0'
  echo $''
  echo $'  local word'
  echo $'  for word in "${non_options[@]}"; do'
  echo $'    case "$node_id:$word" in'
  echo $'      0:update)'
  echo $'        node_id=1'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:u)'
  echo $'        node_id=1'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:install)'
  echo $'        node_id=2'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:add)'
  echo $'        node_id=2'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:remove)'
  echo $'        node_id=3'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:rm)'
  echo $'        node_id=3'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:update-keys)'
  echo $'        node_id=4'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:keys)'
  echo $'        node_id=4'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:list)'
  echo $'        node_id=5'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:ls)'
  echo $'        node_id=5'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:info)'
  echo $'        node_id=6'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:search)'
  echo $'        node_id=7'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:provides)'
  echo $'        node_id=8'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:browse)'
  echo $'        node_id=9'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:origin)'
  echo $'        node_id=10'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      0:completions)'
  echo $'        node_id=11'
  echo $'        node_word_count=1'
  echo $'        ;;'
  echo $'      *)'
  echo $'        break'
  echo $'        ;;'
  echo $'    esac'
  echo $'  done'
  echo $''
  echo $'  positional_index=$((${#non_options[@]} - node_word_count))'
  echo $'}'
  echo $''
  echo $'_pm_completions() {'
  echo $'  local cur=${COMP_WORDS[COMP_CWORD]}'
  echo $'  local prev='
  echo $'  if ((COMP_CWORD > 0)); then'
  echo $'    prev=${COMP_WORDS[$((COMP_CWORD - 1))]}'
  echo $'  fi'
  echo $''
  echo $'  local completed=()'
  echo $'  if ((COMP_CWORD > 1)); then'
  echo $'    completed=("${COMP_WORDS[@]:1:$((COMP_CWORD - 1))}")'
  echo $'  fi'
  echo $''
  echo $'  local non_options=()'
  echo $'  local completed_options=()'
  echo $'  local node_id='
  echo $'  local node_word_count=-1'
  echo $'  local positional_index=0'
  echo $'  local invalid_completion=0'
  echo $'  local flag_state=0'
  echo $'  _pm_completions_resolve_node'
  echo $''
  echo $'  local skip_next=0'
  echo $'  for word in "${completed[@]}"; do'
  echo $'    if ((skip_next)); then'
  echo $'      skip_next=0'
  echo $'      continue'
  echo $'    fi'
  echo $''
  echo $'    if [[ "${word:0:1}" == "-" ]]; then'
  echo $'      _pm_completions_node_flag_state "$node_id" "$word"'
  echo $'      flag_state=$?'
  echo $'      if (( flag_state == 1 )); then'
  echo $'        invalid_completion=1'
  echo $'        break'
  echo $'      fi'
  echo $''
  echo $'      completed_options+=("$word")'
  echo $'      if (( flag_state == 2 )); then'
  echo $'        skip_next=1'
  echo $'      fi'
  echo $'      continue'
  echo $'    fi'
  echo $''
  echo $'    non_options+=("$word")'
  echo $'    _pm_completions_resolve_node'
  echo $'  done'
  echo $''
  echo $'  COMPREPLY=()'
  echo $'  (( invalid_completion )) && return'
  echo $''
  echo $'  case "$node_id:$prev" in'
  echo $'  esac'
  echo $''
  echo $'  if [[ "${cur:0:1}" != "-" ]] && (( positional_index == 0 )); then'
  echo $'    case "$node_id" in'
  echo $'      0)'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "update u install add remove rm update-keys keys list ls info search provides browse origin completions" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'    esac'
  echo $'  fi'
  echo $''
  echo $'  if [[ "${cur:0:1}" == "-" ]]; then'
  echo $'    case "$node_id" in'
  echo $'      0)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        _pm_completions_option_seen "--version" "-v" || words+=("--version" "-v")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      1)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      2)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      3)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      4)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      5)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        _pm_completions_option_seen "--available" "-a" || words+=("--available" "-a")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      6)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        _pm_completions_option_seen "--available" "-a" || words+=("--available" "-a")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      7)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        _pm_completions_option_seen "--available" "-a" || words+=("--available" "-a")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      8)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      9)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        _pm_completions_option_seen "--available" "-a" || words+=("--available" "-a")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      10)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'      11)'
  echo $'        local words=()'
  echo $'        _pm_completions_option_seen "--help" "-h" || words+=("--help" "-h")'
  echo $'        while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "${words[*]}" -- "$cur")'
  echo $'        return'
  echo $'        ;;'
  echo $'    esac'
  echo $'  fi'
  echo $''
  echo $'  if [[ "$node_id" == "2" ]] && (( positional_index >= 0 )); then'
  echo $'    while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(pm list --available)" -- "$cur")'
  echo $'    return'
  echo $'  fi'
  echo $''
  echo $'  if [[ "$node_id" == "3" ]] && (( positional_index >= 0 )); then'
  echo $'    while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(pm list)" -- "$cur")'
  echo $'    return'
  echo $'  fi'
  echo $''
  echo $'  if [[ "$node_id" == "6" ]] && (( positional_index >= 0 )); then'
  echo $'    while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(if _pm_completions_option_seen --available -a; then pm list --available; else pm list; fi)" -- "$cur")'
  echo $'    return'
  echo $'  fi'
  echo $''
  echo $'  if [[ "$node_id" == "7" ]] && (( positional_index >= 0 )); then'
  echo $'    return'
  echo $'  fi'
  echo $''
  echo $'  if [[ "$node_id" == "10" ]] && (( positional_index >= 0 )); then'
  echo $'    while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -A file -- "$cur")'
  echo $'    return'
  echo $'  fi'
  echo $''
  echo $'  case "$node_id:$positional_index" in'
  echo $'    8:0)'
  echo $'      return'
  echo $'      ;;'
  echo $'  esac'
  echo $'} &&'
  echo $'  complete -F _pm_completions pm'
  echo $''
  echo $'# ex: filetype=sh'
}

pm_update_command() {

  sudo pacman -Syu

}

pm_install_command() {

  packages=()
  eval "packages=(${args[package]})"

  sudo pacman -S "${packages[@]}"

}

pm_remove_command() {

  packages=()
  eval "packages=(${args[package]})"

  sudo pacman -Rs "${packages[@]}"

}

pm_update_keys_command() {

  sudo pacman -Sy --noconfirm archlinux-keyring

}

pm_list_command() {

  if [[ ${args[--available]:-} ]]; then
    pacman -S -l -q
  else
    pacman -Q -q -e
  fi

}

pm_info_command() {

  packages=()
  eval "packages=(${args[package]})"

  if [[ ${args[--available]:-} ]]; then
    operation=-Si
  else
    operation=-Qi
  fi

  pacman "$operation" "${packages[@]}"

}

pm_search_command() {

  queries=()
  eval "queries=(${args[query]})"

  if [[ ${args[--available]:-} ]]; then
    operation=-Ss
  else
    operation=-Qs
  fi

  pacman "$operation" "${queries[@]}"

}

pm_provides_command() {

  pkgfile -b "${args[command]}"

}

pm_browse_command() {

  if [[ ${args[--available]:-} ]]; then
    pacman -S -l -q | fzf \
      --preview 'pacman -Si {}' \
      --layout=reverse \
      --bind 'enter:execute(pacman -Si {} | less)'
  else
    pacman -Qq | fzf \
      --preview 'pacman -Qil {}' \
      --layout=reverse \
      --bind 'enter:execute(pacman -Qil {} | less)'
  fi

}

pm_origin_command() {

  paths=()
  eval "paths=(${args[path]})"

  pacman -Qo "${paths[@]}"

}

pm_completions_command() {

  send_completions

}

parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --version | -v)
        version_command
        exit
        ;;

      --help | -h)
        long_usage=yes
        pm_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v pacman >/dev/null 2>&1; then
    printf "missing dependency: pacman\n" >&2
    printf "%s\n\n" "pm requires pacman and is intended for Arch Linux" >&2
    missing_deps=1
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action=${1:-}

  case $action in
    -*) ;;

    update | u)
      action="update"
      shift
      pm_update_parse_requirements "$@"
      shift $#
      ;;

    install | add)
      action="install"
      shift
      pm_install_parse_requirements "$@"
      shift $#
      ;;

    remove | rm)
      action="remove"
      shift
      pm_remove_parse_requirements "$@"
      shift $#
      ;;

    update-keys | keys)
      action="update-keys"
      shift
      pm_update_keys_parse_requirements "$@"
      shift $#
      ;;

    list | ls)
      action="list"
      shift
      pm_list_parse_requirements "$@"
      shift $#
      ;;

    info)
      action="info"
      shift
      pm_info_parse_requirements "$@"
      shift $#
      ;;

    search)
      action="search"
      shift
      pm_search_parse_requirements "$@"
      shift $#
      ;;

    provides)
      action="provides"
      shift
      pm_provides_parse_requirements "$@"
      shift $#
      ;;

    browse)
      action="browse"
      shift
      pm_browse_parse_requirements "$@"
      shift $#
      ;;

    origin)
      action="origin"
      shift
      pm_origin_parse_requirements "$@"
      shift $#
      ;;

    completions)
      action="completions"
      shift
      pm_completions_parse_requirements "$@"
      shift $#
      ;;

    "")
      pm_usage >&2
      exit 1
      ;;

    *)
      printf "invalid command: %s\n" "$action" >&2
      exit 1
      ;;

  esac

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

pm_update_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_update_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="update"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

pm_install_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_install_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="install"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['package']+x} ]]; then
          args['package']="$escaped"
        else
          args['package']="${args['package']} $escaped"

        fi
        shift

        ;;

    esac
  done

  if [[ -z ${args['package']+x} ]]; then
    printf "missing required argument: PACKAGE\nusage: pm install PACKAGE...\n" >&2

    printf "examples:\n" >&2
    printf "  pm install git\n" >&2
    printf "  pm install git fzf\n" >&2

    exit 1
  fi

}

pm_remove_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_remove_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="remove"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['package']+x} ]]; then
          args['package']="$escaped"
        else
          args['package']="${args['package']} $escaped"

        fi
        shift

        ;;

    esac
  done

  if [[ -z ${args['package']+x} ]]; then
    printf "missing required argument: PACKAGE\nusage: pm remove PACKAGE...\n" >&2

    printf "examples:\n" >&2
    printf "  pm remove git\n" >&2

    exit 1
  fi

}

pm_update_keys_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_update_keys_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="update-keys"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

pm_list_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_list_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="list"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --available | -a)

        args['--available']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

pm_info_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_info_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="info"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --available | -a)

        args['--available']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['package']+x} ]]; then
          args['package']="$escaped"
        else
          args['package']="${args['package']} $escaped"

        fi
        shift

        ;;

    esac
  done

  if [[ -z ${args['package']+x} ]]; then
    printf "missing required argument: PACKAGE\nusage: pm info PACKAGE... [OPTIONS]\n" >&2

    printf "examples:\n" >&2
    printf "  pm info git\n" >&2
    printf "  pm info git --available\n" >&2

    exit 1
  fi

}

pm_search_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_search_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="search"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --available | -a)

        args['--available']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['query']+x} ]]; then
          args['query']="$escaped"
        else
          args['query']="${args['query']} $escaped"

        fi
        shift

        ;;

    esac
  done

  if [[ -z ${args['query']+x} ]]; then
    printf "missing required argument: QUERY\nusage: pm search QUERY... [OPTIONS]\n" >&2

    printf "examples:\n" >&2
    printf "  pm search terminal emulator\n" >&2
    printf "  pm search terminal emulator --available\n" >&2

    exit 1
  fi

}

pm_provides_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_provides_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v pkgfile >/dev/null 2>&1; then
    printf "missing dependency: pkgfile\n" >&2
    printf "%s\n\n" "Install with $(magenta pm install pkgfile)" >&2
    missing_deps=1
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="provides"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        if [[ -z ${args['command']+x} ]]; then
          args['command']=$1
          shift
        else
          printf "invalid argument: %s\n" "$key" >&2
          exit 1
        fi

        ;;

    esac
  done

  if [[ -z ${args['command']+x} ]]; then
    printf "missing required argument: COMMAND\nusage: pm provides COMMAND\n" >&2

    printf "examples:\n" >&2
    printf "  pm provides convert\n" >&2

    exit 1
  fi

}

pm_browse_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_browse_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  missing_deps=

  if ! command -v fzf >/dev/null 2>&1; then
    printf "missing dependency: fzf\n" >&2
    printf "%s\n\n" "Install with $(magenta pm install fzf)" >&2
    missing_deps=1
  fi

  if ! command -v less >/dev/null 2>&1; then
    printf "missing dependency: less\n" >&2
    printf "%s\n\n" "Install with $(magenta pm install less)" >&2
    missing_deps=1
  fi

  if [[ -n $missing_deps ]]; then
    exit 1
  fi

  action="browse"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      --available | -a)

        args['--available']=1
        shift
        ;;

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

pm_origin_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_origin_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="origin"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        escaped="$(printf '%q' "$1")"
        if [[ -z ${args['path']+x} ]]; then
          args['path']="$escaped"
        else
          args['path']="${args['path']} $escaped"

        fi
        shift

        ;;

    esac
  done

  if [[ -z ${args['path']+x} ]]; then
    printf "missing required argument: PATH\nusage: pm origin PATH...\n" >&2

    printf "examples:\n" >&2
    printf "  pm origin /usr/bin/git\n" >&2

    exit 1
  fi

}

pm_completions_parse_requirements() {
  local key

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in
      --help | -h)
        long_usage=yes
        pm_completions_usage
        exit
        ;;

      *)
        break
        ;;

    esac
  done

  action="completions"

  while [[ $# -gt 0 ]]; do
    key="$1"
    case "$key" in

      -?*)
        printf "invalid option: %s\n" "$key" >&2
        exit 1
        ;;

      *)

        printf "invalid argument: %s\n" "$key" >&2
        exit 1

        ;;

    esac
  done

}

initialize() {
  declare -g version="0.1.0"
  set -euo pipefail

}

run() {

  declare -g long_usage=''
  declare -g -A args=()
  declare -g -a input=()

  normalize_input "$@"
  parse_requirements "${input[@]}"

  case "$action" in
    "update") pm_update_command ;;
    "install") pm_install_command ;;
    "remove") pm_remove_command ;;
    "update-keys") pm_update_keys_command ;;
    "list") pm_list_command ;;
    "info") pm_info_command ;;
    "search") pm_search_command ;;
    "provides") pm_provides_command ;;
    "browse") pm_browse_command ;;
    "origin") pm_origin_command ;;
    "completions") pm_completions_command ;;
  esac
}

command_line_args=("$@")
initialize
run "${command_line_args[@]}"
