name: Test

on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Install dependencies
      run: pacman -Syu --noconfirm curl shellcheck shfmt

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Shellkin
      run: curl -Ls get.dannyb.co/shellkin/setup | bash

    - name: Run shellcheck
      run: shellcheck pm setup uninstall

    - name: Run shfmt
      run: shfmt -ci -i 2 -d pm setup uninstall

    - name: Run feature tests
      run: shellkin
